In [1]:
import torch
import torch.nn as nn

In [64]:
conv1=nn.Conv1d(
    in_channels=1,
    out_channels=256,
    kernel_size=2,
    stride=1,
    padding=0,
    bias=False
)
ReLU=nn.ReLU()

In [66]:
val=torch.rand(64,1,16002)

In [63]:
val.size()

torch.Size([1, 64, 16002])

In [58]:
val

tensor([[5., 3., 7.]])

In [59]:
list(conv1.parameters())

[Parameter containing:
 tensor([[[-0.3758, -0.5140]],
 
         [[ 0.4091, -0.0743]],
 
         [[-0.1067,  0.3019]]], requires_grad=True)]

In [67]:
conv1(val).size()

torch.Size([64, 256, 16001])

In [50]:
ReLU(conv1(val))

tensor([[0.0000, 0.0000],
        [0.3160, 0.0000],
        [0.0000, 0.2230]], grad_fn=<ReluBackward0>)